src/noisebridge.pyclass/noisebridge/pyclass/todo/urls.py
from django.conf.urls.defaults import patterns, url
from django.views.generic import ListView, CreateView

from pyclass.todo.models import ToDoItem, Tag
from pyclass.todo.views import AddToDo, ToDoDetailView, ToDoMethodCall

urlpatterns = patterns('pyclass.todo.views',
    #url(r'^$', 'pyclass.views.index'),
    url(r'^details/(?P<pk>\d+)/$', ToDoDetailView.as_view(), name="todoitem_details"),
    url(r'^list/$', ListView.as_view(model=ToDoItem, paginate_by=20), name="todo_list"),
    url(r'^add/$', AddToDo.as_view(), name="add_todo"),
    url(r'^add/tag/$', CreateView.as_view(model=Tag), name="add_tag"),
    url(r'^methods/(?P<pk>\d+)/(?P<method>\w+)/$', ToDoMethodCall.as_view(), name="todoitem_methods"),
    url(r'^whatcanido/$', "whatcanido", name="whatcanido"),
    url(r'^tag/(?P<tag>\w+)/$', 'tag_detail', name="tag_detail"),
)

src/noisebridge.pyclass/noisebridge/pyclass/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'pyclass.views.index'),
    url(r'^profile/', include('pyclass.profiles.urls')),
    url(r'^todo/', include('pyclass.todo.urls')),
    url(r'^comments/', include('django.contrib.comments.urls')),
    # Enables the default backend for django-registration.
    # TODO Set up (or remove) Site and correct e-mail and password before using
    # url(r'^accounts/', include('registration.backends.default.urls')),

    # Url for search form in navbar
    url(r'^search/', 'pyclass.views.search'),

    #Simplified registration (no email sent)
    url(r'^accounts/', include('registration.backends.simple.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),


) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/noisebridge.pyclass/noisebridge/pyclass/todo/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from pyclass.profiles.models import Interest


class Tag(models.Model):
    """A descriptive item that is not necessarily an interest"""
    name = models.CharField(max_length=30, unique=True)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ["name"]

    @models.permalink
    def get_absolute_url(self):
        return ('tag_detail', [str(self.id)])


class ToDoItem(models.Model):
    IMPORTANCE_CHOICES = (
        (3, "High"),
        (2, "Medium"),
        (1, "Low"),
        (0, "None")
    )
    STATUS_CHOICES = (
        ("O", "Open"),
        ("IP", "In Progress"),
        ("C", "Completed")
    )
    name = models.CharField(max_length=150)
    details = models.TextField(default="", blank=True)
    excellence = models.PositiveIntegerField(default=0)
    importance = models.IntegerField(max_length=1, choices=IMPORTANCE_CHOICES, default="0")
    due = models.DateField(blank=True, null=True)
    status = models.CharField(max_length=2, choices=STATUS_CHOICES, default="O")
    completed_by = models.ForeignKey(User, blank=True, null=True, related_name='todos_completed')
    completion_date = models.DateTimeField(blank=True, null=True, editable=False)
    interests = models.ManyToManyField(Interest, blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    users_claimed = models.ManyToManyField(User, blank=True, related_name='todos_claimed')
    # FIXME Currently broken. Do not use. Needs some sort of tree structure to be implemented correctly.
    sub_tasks = models.ManyToManyField("self", blank=True, related_name='parent_task')
    creator = models.ForeignKey(User, related_name='todos_created')
    creation_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
            return self.name

    class Meta:
        get_latest_by = "creation_date"
        ordering = ["-creation_date"]

    def save(self, user=None, *args, **kwargs):
        # Only adds a creator when the object is first created
        if user and not self.id:
            self.creator = user
        super(ToDoItem, self).save(*args, **kwargs)  # Call the "real" save() method.

    @models.permalink
    def get_absolute_url(self):
        return ('todoitem_details', [str(self.id)])

    @method_decorator(login_required)
    def complete(self, request, user):
        """Marks the item as completed and assigns it's excellence to the user"""
        if self.status != "C":
            self.status = "C"
            self.completed_by = user
            self.completion_date = datetime.now()
            self.save()
            user.userprofile.excellence += self.excellence
            user.userprofile.save()
            return True
        return False

    @method_decorator(login_required)
    def claim(self, request, user):
        """Allows a user to claim the item"""
        if self.status != "C":
            self.status = "IP"
            self.users_claimed.add(user)
            self.save()
            return True
        return False

src/noisebridge.pyclass/noisebridge/pyclass/todo/forms.py
from django import forms

from pyclass.todo.models import ToDoItem


class ToDoItemForm(forms.ModelForm):
    class Meta:
        model = ToDoItem
        fields = ("name", "details", "excellence", "importance", "due", "interests", "tags")

src/noisebridge.pyclass/noisebridge/pyclass/todo/views.py
import datetime

from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import DetailView
from django.views.generic.base import View
from django.views.generic.edit import CreateView

from pyclass.todo.models import ToDoItem
from pyclass.todo.forms import ToDoItemForm


class AddToDo(CreateView):
    model = ToDoItem
    form_class = ToDoItemForm

    def form_valid(self, form):
        todo = form.save(commit=False)
        # Must be passed to populate the "creator" field, which is required.
        todo.save(self.request.user)
        # Won't save many-to-many fields properly without this line
        form.save_m2m()
        messages.success(self.request, "Task added")
        return redirect(todo)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AddToDo, self).dispatch(*args, **kwargs)


class ToDoDetailView(DetailView):
    model = ToDoItem

    def get_context_data(self, **kwargs):
        #Add additional data to the context to display date in a non-awkward sounding way
        context = super(ToDoDetailView, self).get_context_data(**kwargs)
        todo = super(ToDoDetailView, self).get_object()
        today = datetime.datetime.now().date()

        creation_date = todo.creation_date
        context["creation_date"] = creation_date

        creation_date_offset = abs(creation_date.date() - today).days > 1
        context["creation_date_offset"] = creation_date_offset

        if todo.completion_date:
            completion_date = todo.completion_date
            context["completion_date"] = completion_date

            completion_date_offset = abs(completion_date.date() - today).days > 1
            context["completion_date_offset"] = completion_date_offset
        return context


class ToDoMethodCall(View):
    """Processes incoming method calls for ToDoItem objects"""

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ToDoMethodCall, self).dispatch(*args, **kwargs)

    def get(self, *args, **kwargs):
        todo = ToDoItem.objects.get(pk=kwargs["pk"])
        method = kwargs["method"]
        if method == "claim":
            # This might look unnecessary, but it prevents methods without the
            # same name as their action from looking weird
            action = "claim"
        elif method == "complete":
            action = "complete"
        else:
            messages.error(self.request, "Invalid method specified")
            return redirect(todo)
        context = {"title": "{0} ToDo".format(action.capitalize()),
                   "message": "Are you sure you want to {0}\
                        <strong>{1}</strong> ?".format(action, todo.name)}
        return render(self.request, "confirm_action.html", context)

    def post(self, *args, **kwargs):
        todo = ToDoItem.objects.get(pk=kwargs["pk"])
        method = kwargs["method"]
        user = self.request.user
        if method == "claim":
            todo.claim(self.request, user)
            messages.success(self.request, "ToDo claimed")
        elif method == "complete":
            todo.complete(self.request, user)
            messages.success(self.request, "ToDo completed")
        return redirect(todo)


@login_required
def whatcanido(request):
    cando_list = ToDoItem.objects.all()
    return render(request, "todo/todoitem_list.html", {"todoitem_list": cando_list})


def tag_detail(request, tag):
    return render(request, "todo/tag_detail.html")

src/noisebridge.pyclass/noisebridge/pyclass/todo/templates/todo/tag_detail.html
{% extends "base.html" %}

{% block content %}
    <ul>
        {% for todo in todoitem_list %}
            <li><a href="{{ todo.get_absolute_url }}">{{ todo.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

src/noisebridge.pyclass/noisebridge/pyclass/todo/templates/todo/tag_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
    Add Tag
{% endblock title %}

{% block content %}
    <h1>Add Tag</h1>
    <form action="." method="post">
        {% csrf_token %}
        <table>
            {{ form|crispy }}
        </table>
        <input type="submit" value="Add Tag">
    </form>
{% endblock content %}

src/noisebridge.pyclass/noisebridge/pyclass/todo/templates/todo/todoitem_detail.html
{% extends "base.html" %}
{% load humanize %}
{% load comments %}

{% block content %}
    <h1>{{ todoitem.name }}</h1>
    <p>{{ todoitem.details }}</p>
	<p>Created by: {{ todoitem.creator }}
        {# Determine how best to display the date. creation_date_offset will be True if #}
        {# the date is within one day of now. #}
        {% if creation_date_offset %}
            on
        {% endif %}
        {{ creation_date.date|naturalday }} at
        {{ creation_date.time }}</p>
    <p>Excellence: {{ todoitem.excellence }}</p>
    <p>Due: {{todoitem.due|naturalday }}</p>
    <p>Importance: {{ todoitem.get_importance_display }}</p>
    <p>Status: {{ todoitem.get_status_display }}</p>
    {% if todoitem.status == 'C' %}
        <p>Completed by: {{ todoitem.completed_by }}
            {# See above for created #}
            {% if completion_date_offset %}
                on
            {% endif %}
            {{ completion_date.date|naturalday }} at
            {{ completion_date.time}}</p>
    {% endif %}

    <h2>Interests</h2>
    <ul>
    {% for interest in todoitem.interests.all %}
        <li><a href={{ "interest.get_absolute_url" }}>{{ interest.name }}</a></li>
    {% empty %}
        This task has no interests defined.
    {% endfor %}
    </ul>

    <h2>Tags</h2>
    <ul>
    {% for tag in todoitem.tags.all %}
        <li><a href={{ "tag.get_absolute_url" }}>{{ tag.name }}</a></li>
    {% empty %}
        This task has no tags defined.
    {% endfor %}
    </ul>

    {% with claims=todoitem.users_claimed.all %}
        <h2>Claims</h2>
        <ul>
        {% for user in claims %}
            <li><a href={{ "user.get_absolute_url" }}>{{ user.username }}</a></li>
        {% empty %}
            This task has not been claimed by anyone.
        {% endfor %}
        </ul>

        {% if todoitem.status != 'C' %}
            {% if not user in claims %}
                <a href="{% url todoitem_methods pk=todoitem.pk method='claim' %}">Claim Task</a>
            {% endif %}
            <a href="{% url todoitem_methods pk=todoitem.pk method='complete' %}">Complete Task</a>
        {% endif %}
    {% endwith %}

    {% get_comment_count for todoitem as comment_count %}
    <hr>
    <p>This item has {{ comment_count }} comment{{ comment_count|pluralize }}.</p>
    {% render_comment_list for todoitem %}
    <hr>
    <p>Add a comment</p>
    {% render_comment_form for todoitem %}
{% endblock content %}

src/noisebridge.pyclass/noisebridge/pyclass/todo/templates/todo/todoitem_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
    Add Task
{% endblock title %}

{% block content %}
    <h1>Add Todo</h1>
    <form action="." method="post">
        {% csrf_token %}
        <table>
            {{ form|crispy }}
        </table>
        <input type="submit" value="Add Task">
    </form>
{% endblock content %}

src/noisebridge.pyclass/noisebridge/pyclass/todo/templates/todo/todoitem_list.html
{% extends "base.html" %}

{% block title %}
    ToDo List- Page {{ page }}
{% endblock title %}

{% block content %}
    <ul>
        {% for todo in todoitem_list %}
            <li><a href="{{ todo.get_absolute_url }}">{{ todo.name }}</a></li>
        {% endfor %}
    </ul>
    {% if is_paginated %}
        <div class="pagination pagination-centered">
            <ul>
                {% if page_obj.has_previous %}
                    <li><a href="?page=1">first</a></li>
                    <li><a href="?page={{ page_obj.previous_page_number }}">previous</a></li>
                {% endif %}
                {% with page_obj.number as current_page  %}
                    {% for page in paginator.page_range %}
                        {% if page == current_page %}
                            <li class="active"><a href="?page={{ page }}" class="page_link">{{ page }}</a></li>
                        {% else %}
                            <li><a href="?page={{ page }}" class="page_link">{{ page }}</a></li>
                        {% endif %}
                    {% endfor %}
                {% endwith %}
                {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}">next</a></li>
                    <li><a href="?page=last">last</a></li>
                {% endif %}
            </ul>
        </div>
    {% endif %}
{% endblock content %}

src/noisebridge.pyclass/noisebridge/pyclass/todo/templates/todo/todoitem_tags.html
{% extends "base.html" %}

{% block content %}
    <ul>
        {% for todo in todoitem_list %}
            <li><a href="{{ todo.get_absolute_url }}">{{ todo.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

src/noisebridge.pyclass/noisebridge/pyclass/todo/templates/todo/todoitem_whatcanido.html
{% extends "base.html" %}

{% block content %}
    <ul>
        {% for todo in todoitem_list %}
            <li><a href="{{ todo.get_absolute_url }}">{{ todo.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}