src/noisebridge.pyclass/noisebridge/pyclass/profiles/urls.py
from django.conf.urls.defaults import patterns, url
from django.views.generic import DetailView

from pyclass.profiles.models import Interest

urlpatterns = patterns('pyclass.profiles.views',
    #url(r'^$', 'pyclass.views.index'),
    url(r'^settings/$', 'update_settings', name="user_settings"),
    url(r'^add/interest/$', 'add_interests', name="add_interest"),
    url(r'^search/interests/$', 'search_interests', name="search_interests"),
    url(r'^reset_avatar/$', 'reset_avatar', name="reset_avatar"),
    url(r'^interest/(?P<pk>\d+)/$', DetailView.as_view(model=Interest), name="interest_details"),
    url(r'^(?P<user_name>\w+)/$', 'display_profile'),
)

src/noisebridge.pyclass/noisebridge/pyclass/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'pyclass.views.index'),
    url(r'^profile/', include('pyclass.profiles.urls')),
    url(r'^todo/', include('pyclass.todo.urls')),
    url(r'^comments/', include('django.contrib.comments.urls')),
    # Enables the default backend for django-registration.
    # TODO Set up (or remove) Site and correct e-mail and password before using
    # url(r'^accounts/', include('registration.backends.default.urls')),

    # Url for search form in navbar
    url(r'^search/', 'pyclass.views.search'),

    #Simplified registration (no email sent)
    url(r'^accounts/', include('registration.backends.simple.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),


) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/noisebridge.pyclass/noisebridge/pyclass/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.conf import settings


class Interest(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ["name"]

    @models.permalink
    def get_absolute_url(self):
        return ('interest_details', [str(self.id)])


class UserProfile(models.Model):
    DEFAULT_AVATAR = settings.STATIC_URL + "default-avatar.png"
    user = models.OneToOneField(User)
    avatar = models.ImageField(upload_to="avatars",
                               default=DEFAULT_AVATAR)
    biography = models.TextField(default='', blank=True)
    interests = models.ManyToManyField(Interest)
    excellence = models.PositiveIntegerField(default=0)

    def __unicode__(self):
        return self.user.username

    class Meta:
        ordering = ["user"]

    def reset_avatar(self):
        self.avatar = self.DEFAULT_AVATAR
        self.save()


def create_user_profile(sender, instance, created, **kwargs):
    """Create the UserProfile when a new User is saved"""
    if created:
        profile = UserProfile()
        profile.user = instance
        profile.save()

post_save.connect(create_user_profile, sender=User)

src/noisebridge.pyclass/noisebridge/pyclass/profiles/forms.py
from django import forms
from django.contrib.auth.models import User

from pyclass.fields import CommaSeparatedCharField
from pyclass.profiles.models import UserProfile


class SearchForm(forms.Form):
    query = forms.CharField(max_length=300,
                            label='Enter search term')
    query_type = forms.ChoiceField(choices=(("interest", "Interest"), ("user", "User"),),
                                   label='Specify type of search')


class AddInterestForm(forms.Form):
    interests = CommaSeparatedCharField(max_length=50)


class UserSettingsForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")


class UserProfileSettingsForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ("avatar", "biography")

src/noisebridge.pyclass/noisebridge/pyclass/profiles/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from pyclass.profiles.models import Interest
from pyclass.profiles.forms import SearchForm, AddInterestForm, UserSettingsForm, UserProfileSettingsForm


def search_interests(request):
    """
    Returns a list with all interests that contain (case insensitive) the string "query".
    """
    if "query" and "query_type" in request.GET:
        form = SearchForm(request.GET)
        if not form.is_valid():
            messages.error(request, "Form contains errors.")
        else:
            cd = form.cleaned_data
            query = cd["query"]
            query_type = cd["query_type"]
            interests = None
            users = None
            if query_type == "interest":
                interests = Interest.objects.filter(name__icontains=query)
            elif query_type == "user":
                users = User.objects.filter(username__icontains=query)
            return render(request, "profiles/search_results.html",
                         {"query": query, "query_type": query_type,
                          "interests": interests, "users": users})
    else:
        form = SearchForm()
    return render(request, "profiles/search_form.html", {"form": form})


@login_required
def add_interests(request):
    """
    Adds interests to the user's profile.
    If an interest doesn't exist, adds it to the database first.
    """
    if request.method == "POST":
        form = AddInterestForm(request.POST)
        if not form.is_valid():
            messages.error(request, "Form contains errors.")
        else:
            profile = request.user.userprofile
            interests = form.cleaned_data["interests"]
            for i in interests:
                interest_list = Interest.objects.filter(name=i).count()
                if not interest_list:
                    interest = Interest(name=i)
                    interest.save()
                else:
                    interest = Interest.objects.get(name=i)
                profile.interests.add(interest)
            profile.save()
            if len(interests) > 1:
                messages.success(request, "Interests added.")
                return redirect(request.user)
            else:
                messages.success(request, "Interest added.")
                return redirect(interest)
    else:
        form = AddInterestForm()
    return render(request, "profiles/addinterest.html", {"form": form})


def display_profile(request, user_name):
    requested_user = None
    profile = None
    if User.objects.filter(username=user_name):
        requested_user = User.objects.get(username=user_name)
        profile = requested_user.userprofile
    return render(request, "profiles/user_profile.html", {"user_name": user_name,
                                                         "requested_user": requested_user,
                                                         "profile": profile})


@login_required
def update_settings(request):
    user = request.user
    profile = user.userprofile
    if request.method == "POST":
        user_form = UserSettingsForm(request.POST, instance=user)
        profile_form = UserProfileSettingsForm(request.POST, request.FILES, instance=profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Profile details updated.")
            return redirect(user)
        else:
            messages.error(request, "Form contains errors.")
    else:
        # Done as two forms because we're using generic model forms
        user_form = UserSettingsForm(initial={
            "first_name": user.first_name,
            "last_name": user.last_name,
            "email": user.email,
        })
        profile_form = UserProfileSettingsForm(initial={
            "avatar": profile.avatar,
            "biography": profile.biography,
        })
    return render(request, "profiles/user_settings.html", {"user_form": user_form, "profile_form": profile_form})


@login_required
def reset_avatar(request):
    if request.method == "POST":
        user = request.user
        user.userprofile.reset_avatar()
        messages.success(request, "Avatar reset.")
        return redirect(user)
    return render(request, "confirm_action.html",
                 {"title": "Reset Avatar",
                 "message": "Are you sure you want to reset your avatar to the default?"
    })

src/noisebridge.pyclass/noisebridge/pyclass/profiles/templates/profiles/addinterest.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
	Add Interests
{% endblock title %}

{% block content %}
	<h2>Add Interests</h2>
	<form action="" method="post">
		{% csrf_token %}
		<table>
            {{ form|crispy }}
        </table>
		<p>Please separate multiple interests with commas, (e.g. "Interest 1, Interest 2")</p>
		<input type="submit" value="Add Interests">
	</form>
{% endblock content %}

src/noisebridge.pyclass/noisebridge/pyclass/profiles/templates/profiles/index.html
This is the default profile page

src/noisebridge.pyclass/noisebridge/pyclass/profiles/templates/profiles/interest_detail.html
{% extends "base.html" %}

{% block title %}
    {{ interest.name }}
{% endblock title %}

{% block content %}
<h1>{{ interest.name }}</h1>
    <ul>
        {% for profile in interest.userprofile_set.all %}
            <li><a href="{{ profile.user.get_absolute_url }}">{{ profile.user.username }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

src/noisebridge.pyclass/noisebridge/pyclass/profiles/templates/profiles/reset_avatar.html
{% extends "base.html" %}
{% block title %}
    Reset Avatar
{% endblock title %}

{% block content %}
    <p>Are you sure you want to reset your avatar to the default?</p>
    <form action="." method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, I'm sure">
    </form>
{% endblock content %}

src/noisebridge.pyclass/noisebridge/pyclass/profiles/templates/profiles/search_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
	Search
{% endblock title %}

{% block content %}
	<h2>Search for Interests</h2>

	<form action="." method="get">
        <table>
            {{ form|crispy }}
        </table>
        <input type="submit" value="Search">
    </form>
{% endblock content %}

src/noisebridge.pyclass/noisebridge/pyclass/profiles/templates/profiles/search_results.html
{% extends "base.html" %}

{% block title %}
	Search Results
{% endblock title %}

{% block content %}
	{% if query_type == "interest" %}
		<p>You searched for interests containing: <strong>{{ query }}</strong></p>
		{% if interests %}
			<p>Found {{ interests|length }} interest{{ interests|pluralize  }} matching your query</p>
				{% for interest in interests %}
					<p>Found {{ interest.userprofile_set.all|length }}
						user{{ interest.userprofile_set.all|pluralize }} with an interest in
						<strong><a href="{{ interest.get_absolute_url }}">{{ interest.name }}</a></strong></p>
					<ul>
					{% for profile in interest.userprofile_set.all %}
			            <li><a href="{{ profile.user.get_absolute_url }}">{{ profile.user.username }}</a></li>
					{% endfor %}
					</ul>
				{% endfor %}
		{% else %}
			<p>No users matched your search criteria.</p>
		{% endif %}
	{% elif query_type == "user" %}
		<p>You searched for users containing: <strong>{{ query }}</strong></p>
		{% if users %}
			<p>Found {{ users|length }} user{{ users|pluralize  }} matching your query</p>
				{% for user in users %}
					<p> User <strong><a href="{{ user.get_absolute_url }}">{{ user }}</a>
						</strong> has the following interests:</p>
					<ul>
					{% for interest in user.userprofile.interests.all %}
						<li><a href="{{ interest.get_absolute_url }}">{{ interest.name }}</a></li>
					{% endfor %}
					</ul>
				{% endfor %}
		{% else %}
			<p>No users matched your search criteria.</p>
		{% endif %}
	{% else %}
		<p>You did not provide any search terms.</p>
	{% endif %}
{% endblock content %}

src/noisebridge.pyclass/noisebridge/pyclass/profiles/templates/profiles/user_profile.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {% if not requested_user %}
        No Such User
    {% else %}
        {{ requested_user.username }}
    {% endif %}
{% endblock title %}

{% block content %}
    {% if not requested_user %}
        <p>User "<strong>{{ user_name }}</strong>" does not exist.</p>
    {% else %}
        <h1>{{ requested_user.username }}
            {% if requested_user.get_full_name %}
                ({{ requested_user.get_full_name }})
            {% endif %}
        </h1>
        <p><img src="{{ profile.avatar.url }}" alt="Avatar"></p>
        <p>E-mail: <a href="mailto:{{ requested_user.email }}">{{ requested_user.email }}</a></p>
        <p>Excellence: {{ profile.excellence }}</p>
        {% if profile.biography %}
            <h2>Bio</h2>
            <p>{{ profile.biography }}</p>
        {% endif %}
        <h2>Interests</h2>
        <ul>
            {% for interest in profile.interests.all %}
                <li><a href="{{ interest.get_absolute_url }}">{{ interest.name }}</a></li>
            {% endfor %}
        </ul>
        <h2>Tasks</h2>
        <hr>
        {# The number of items to display for each category #}
        {% with display=5 %}
            <h3>Tasks Claimed</h3>
            <ul>
                {% for todo in requested_user.todos_claimed.all %}
                    {% if forloop.counter <= display %}
                        <li><a href="{{ todo.get_absolute_url }}">{{ todo.name }}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
            {% if requested_user.todos_claimed.all|length > display %}
                <a href="#">More</a>
            {% endif %}
            <h3>Tasks Created</h3>
            <ul>
                {% for todo in requested_user.todos_created.all %}
                    {% if forloop.counter <= display %}
                        <li><a href="{{ todo.get_absolute_url }}">{{ todo.name }}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
            {% if requested_user.todos_created.all|length > display %}
                <a href="#">More</a>
            {% endif %}
            <h3>Tasks Completed</h3>
            <ul>
                {% for todo in requested_user.todos_completed.all %}
                    {% if forloop.counter <= display %}
                        <li><a href="{{ todo.get_absolute_url }}">{{ todo.name }}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
            {% if requested_user.todos_completed.all|length > display %}
                <a href="#">More</a>
            {% endif %}
        {% endwith %}
    {% endif %}
{% endblock content %}

src/noisebridge.pyclass/noisebridge/pyclass/profiles/templates/profiles/user_settings.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
    {{ user.username }} - Settings
{% endblock title %}

{% block content %}
    <h1>User Settings</h1>
    <a class="btn" href="{% url auth_password_change %}">Change password</a>
    <a class="btn" href="{% url reset_avatar %}">Reset avatar to default</a>
    <form enctype="multipart/form-data" action="." method="post">
        {% csrf_token %}
        <table>
            {{ user_form|crispy }}
            {{ profile_form|crispy }}
        </table>
        <input class="btn btn-primary" type="submit" value="Update Settings">
    </form>
{% endblock content %}